# Generated by Django 2.2.7 on 2020-05-03 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillsetdetailsmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('resume', models.FileField(upload_to='resume', validators=[users.validators.validate_file_extension])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('countryName', django_countries.fields.CountryField(max_length=2)),
                ('dateOfBrith', models.CharField(blank=True, max_length=100, null=True)),
                ('currentLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('panNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('aatharNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('currnetMailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('permanentMailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personaldetailsmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('Employee', 'S'), ('Employer', 'E')], max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('resume', models.FileField(upload_to='resume', validators=[users.validators.validate_file_extension])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EdudetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolX', models.CharField(blank=True, max_length=100, null=True)),
                ('specializationX', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassingX', models.IntegerField(blank=True, null=True)),
                ('scoreX', models.IntegerField(blank=True, null=True)),
                ('schoolXII', models.CharField(blank=True, max_length=100, null=True)),
                ('specializationXII', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassingXII', models.IntegerField(blank=True, null=True)),
                ('scoreXII', models.IntegerField(blank=True, null=True)),
                ('diploma', models.CharField(blank=True, max_length=100, null=True)),
                ('specializationDiploma', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassingDiploma', models.IntegerField(blank=True, null=True)),
                ('scoreDiploma', models.IntegerField(blank=True, null=True)),
                ('UG', models.CharField(blank=True, max_length=100, null=True)),
                ('specializationUG', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassingUG', models.IntegerField(blank=True, null=True)),
                ('scoreUG', models.IntegerField(blank=True, null=True)),
                ('PG', models.CharField(blank=True, max_length=100, null=True)),
                ('specializationPG', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPassingPG', models.IntegerField(blank=True, null=True)),
                ('scorePG', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companydetailsmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
