# Generated by Django 2.2.7 on 2020-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200503_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
