# Generated by Django 2.2.7 on 2020-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200503_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
