# Generated by Django 2.2.7 on 2020-05-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companycode_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
