# Generated by Django 2.2.7 on 2020-05-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permission_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='logo',
            new_name='recruiterpic',
        ),
    ]
