# Generated by Django 2.2.7 on 2020-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical',
            name='dislikelike',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='technical',
            name='like',
            field=models.IntegerField(default=True),
        ),
    ]
