# Generated by Django 2.2.7 on 2020-05-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20200524_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100)),
                ('commentsauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Technical')),
            ],
        ),
    ]
