# Generated by Django 2.2.7 on 2020-05-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedCandiateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candiatename', models.CharField(blank=True, max_length=100, null=True)),
                ('jobid', models.CharField(blank=True, max_length=100, null=True)),
                ('createddate', models.CharField(blank=True, max_length=100, null=True)),
                ('updateddate', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlistedcandiatemodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
