# Generated by Django 2.2.7 on 2020-05-06 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewJobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField(blank=True, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('clientname', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('mandatoryskils', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('expectednoticeperiod', models.CharField(blank=True, max_length=100, null=True)),
                ('jobdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('joblocation', models.CharField(blank=True, max_length=100, null=True)),
                ('contactname', models.CharField(blank=True, max_length=100, null=True)),
                ('contactmailid', models.CharField(blank=True, max_length=100, null=True)),
                ('contactmobilenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('payscalefromlacks', models.IntegerField(blank=True, null=True)),
                ('payscalefromthousand', models.IntegerField(blank=True, null=True)),
                ('payscaletolacks', models.IntegerField(blank=True, null=True)),
                ('payscaletothousand', models.IntegerField(blank=True, null=True)),
                ('contractjob', models.CharField(blank=True, max_length=100, null=True)),
                ('contractfromyear', models.IntegerField(blank=True, null=True)),
                ('contractfrommonth', models.IntegerField(blank=True, null=True)),
                ('contracttoyear', models.IntegerField(blank=True, null=True)),
                ('contracttomonth', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createnewjobmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
