# Generated by Django 2.2.7 on 2020-05-10 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrpanel', '0004_offlinecandiatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCandiateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduleddate', models.CharField(blank=True, max_length=100, null=True)),
                ('candidatename', models.CharField(blank=True, max_length=100, null=True)),
                ('candidatephone', models.CharField(blank=True, max_length=100, null=True)),
                ('candidateemailid', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduledcandiatemodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
